import './globals.css';
import { Inter } from 'next/font/google';
import ClientProvider from '@/redux/provider';
import ModalProvider from '@/components/ModalProvider/ModalProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'The Weather',
  description: 'Generated by create next app for test assignment',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        id="root"
        suppressHydrationWarning={true}
        className={inter.className}
      >
        <ClientProvider>
          <ModalProvider>{children}</ModalProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
